parameters:
- name: azureSvcName
  type: string
- name: aadNameSvc
  type: string
- name: aadObjectidSvc
  type: string
- name: bicepFilePath
  type: string
- name: bicepParameterFilePath
  type: string

stages:
- stage: PrivateEndpoints
  jobs:
  - job: PrivateEndpoints
    variables:
    - template: ./variables.yml
    steps:
    - task: AzureCLI@2
      displayName: Deploy Private Endpoints
      inputs:
        azureSubscription: ${{ parameters.azureSvcName }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          SqlPass=$(az keyvault secret show --vault-name $(KEYVAULT_NAME) --name $(KVSECRET_NAME_SQLPASS) --query value -o tsv)
          az deployment group create --resource-group $(RESOURCE_GROUP_NAME) --template-file ${{ parameters.bicepFilePath }} \
              --parameters ${{ parameters.bicepParameterFilePath }} \
              base_name=$(BASE_NAME) \
              environment_symbol=$(ENVIRONMENT_SYMBOL) \
              aad_name_svc=${{ parameters.aadNameSvc }} \
              aad_objectid_svc=${{ parameters.aadObjectidSvc }} \
              sql_pass=$SqlPass
